<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1658478681163' stop='1658478693581'>
    <name>SuperCalculator test</name>
    <title>SuperCalculator test</title>
    <test-cases>
        <test-case start='1658478682038' status='passed' stop='1658478684536'>
            <name>add test</name>
            <title>add test</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1658478684536' status='failed' stop='1658478686958'>
            <name>add test failure</name>
            <title>add test failure</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Expected '88088' to equal '88089'.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (c:\Users\rohit\Music\Protractor_learning\supercalExample\supcal2.js:49:30)
                    at C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:112:25
                    at new ManagedPromise (C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1077:7)
                    at ControlFlow.promise (C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2505:12)
                    at schedulerExecute (C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\jasminewd2\index.js:95:18)
                    at TaskQueue.execute_ (C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
                    at C:\Users\rohit\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7</stack-trace>
            </failure>
        </test-case>
        <test-case start='1658478686958' status='passed' stop='1658478689367'>
            <name>add test failure</name>
            <title>add test failure</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
        </test-case>
        <test-case start='1658478689367' status='pending' stop='1658478689369'>
            <name>add test failure</name>
            <title>add test failure</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Temporarily disabled with xit</message>
                <stack-trace></stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>